import { describe, expect, it } from "vitest";
import { detectFormat, htmlToText, normalizeTranscript, timecodeToSeconds } from "./normalize.js";

const VTT = `WEBVTT

NOTE this is a comment

1
00:00:00.000 --> 00:00:04.000
<v Alice>Welcome to the show.

00:00:04.000 --> 00:00:08.000
<v Bob>Thanks for having me.

00:00:08.000 --> 00:00:12.000
<v Bob>Thanks for having me.
`;

const VTT_WITH_HEADER_CUE = `WEBVTT - Generated by Example
00:00:00.000 --> 00:00:02.000
Hello from the first cue.
`;

const SRT = `1
00:00:00,000 --> 00:00:04,000
Alice: Welcome to the show.

2
00:00:04,000 --> 00:00:08,000
It is <i>great</i> to be here.
`;

const JSON_TRANSCRIPT = JSON.stringify({
  version: "1.0.0",
  segments: [
    { startTime: 0, endTime: 4, speaker: "Alice", body: "Welcome to the show." },
    { startTime: 4, endTime: 8, speaker: "Bob", body: "Thanks for having me." },
  ],
});

describe("detectFormat", () => {
  it("uses the MIME type first", () => {
    expect(detectFormat({ contentType: "text/vtt", body: "anything" })).toBe("vtt");
    expect(detectFormat({ contentType: "application/x-subrip", body: "x" })).toBe("srt");
  });

  it("falls back to URL extension, then content sniffing", () => {
    expect(detectFormat({ url: "https://a/t.srt?x=1", body: "x" })).toBe("srt");
    expect(detectFormat({ body: VTT })).toBe("vtt");
    expect(detectFormat({ body: SRT })).toBe("srt");
    expect(detectFormat({ body: JSON_TRANSCRIPT })).toBe("json");
    expect(detectFormat({ body: "<html><body>hi</body></html>" })).toBe("html");
    expect(detectFormat({ body: "plain words here" })).toBe("txt");
  });
});

describe("timecodeToSeconds", () => {
  it("parses HH:MM:SS.mmm, MM:SS, comma-decimal, and bare-seconds forms", () => {
    expect(timecodeToSeconds("00:01:30.500")).toBe(90.5);
    expect(timecodeToSeconds("01:30")).toBe(90);
    expect(timecodeToSeconds("00:00:01,200")).toBe(1.2);
    expect(timecodeToSeconds("2.5")).toBe(2.5);
  });

  it("ignores trailing SRT cue settings/position coordinates", () => {
    expect(timecodeToSeconds("00:00:02,000 X1:40 X2:600")).toBe(2);
  });

  it("returns undefined for unparseable input", () => {
    expect(timecodeToSeconds("not a timecode")).toBeUndefined();
    expect(timecodeToSeconds("")).toBeUndefined();
  });
});

describe("normalizeTranscript", () => {
  it("parses VTT with voice tags, skipping headers and duplicate cues", () => {
    const result = normalizeTranscript(VTT, "vtt");
    expect(result.text).toContain("Alice: Welcome to the show.");
    expect(result.text).toContain("Bob: Thanks for having me.");
    expect(result.text.match(/Thanks for having me/g)).toHaveLength(1);
    expect(result.segments?.[0]).toMatchObject({
      speaker: "Alice",
      start: "00:00:00.000",
      startSeconds: 0,
      endSeconds: 4,
    });
  });

  it("parses a VTT whose first cue follows the WEBVTT header without a blank line", () => {
    const result = normalizeTranscript(VTT_WITH_HEADER_CUE, "vtt");
    expect(result.text).toBe("Hello from the first cue.");
    expect(result.segments).toHaveLength(1);
  });

  it("parses SRT with speaker prefixes and strips formatting tags", () => {
    const result = normalizeTranscript(SRT, "srt");
    expect(result.text).toContain("Alice: Welcome to the show.");
    expect(result.text).toContain("It is great to be here.");
    expect(result.text).not.toContain("<i>");
    expect(result.segments).toHaveLength(2);
    expect(result.segments?.[0]).toMatchObject({ speaker: "Alice", startSeconds: 0, endSeconds: 4 });
  });

  it("parses SRT startSeconds/endSeconds even when the cue timing carries trailing position coordinates", () => {
    const srtWithCoords = `1\n00:00:00,000 --> 00:00:02,000 X1:40 X2:600 Y1:20 Y2:50\nPositioned caption.\n`;
    const result = normalizeTranscript(srtWithCoords, "srt");
    expect(result.segments?.[0]).toMatchObject({ startSeconds: 0, endSeconds: 2 });
  });

  it("parses podcast-namespace JSON segments", () => {
    const result = normalizeTranscript(JSON_TRANSCRIPT, "json");
    expect(result.text).toContain("Alice: Welcome to the show.");
    expect(result.text).toContain("Bob: Thanks for having me.");
    expect(result.segments).toHaveLength(2);
    expect(result.segments?.[0]).toMatchObject({ startSeconds: 0, endSeconds: 4 });
  });

  it("parses fractional-second JSON startTime/endTime as-is", () => {
    const result = normalizeTranscript(
      JSON.stringify({ segments: [{ startTime: 0.5, endTime: 2.25, body: "Fractional." }] }),
      "json",
    );
    expect(result.segments?.[0]).toMatchObject({ startSeconds: 0.5, endSeconds: 2.25 });
  });

  it("throws a clear error for malformed JSON", () => {
    expect(() => normalizeTranscript("not json", "json")).toThrowError(/could not be parsed/);
    expect(() => normalizeTranscript("{}", "json")).toThrowError(/usable transcript/);
  });

  it("parses whisper.cpp's -oj/-ojf JSON shape (nested transcription/offsets, issue #53)", () => {
    const whisperCppJson = JSON.stringify({
      transcription: [
        { text: "Hello from whisper.cpp.", offsets: { from: 0, to: 1200 } },
        { text: "Second segment.", timestamps: { from: "00:00:01,200", to: "00:00:02,400" } },
      ],
    });
    const result = normalizeTranscript(whisperCppJson, "json");
    expect(result.text).toContain("Hello from whisper.cpp.");
    expect(result.text).toContain("Second segment.");
    expect(result.segments).toHaveLength(2);
    expect(result.segments?.[0]).toMatchObject({ start: "0", end: "1200", startSeconds: 0, endSeconds: 1.2 });
    expect(result.segments?.[1]).toMatchObject({
      start: "00:00:01,200",
      end: "00:00:02,400",
      startSeconds: 1.2,
      endSeconds: 2.4,
    });
  });

  it("parses numeric nested timestamps.from/to as seconds (not just string timecodes)", () => {
    const result = normalizeTranscript(
      JSON.stringify({
        segments: [{ text: "Numeric nested timing.", timestamps: { from: 12.5, to: 18 } }],
      }),
      "json",
    );
    expect(result.segments?.[0]).toMatchObject({ startSeconds: 12.5, endSeconds: 18 });
  });

  it("parses common non-standard JSON transcript shapes", () => {
    const stringArray = normalizeTranscript(JSON.stringify({ transcript: ["First paragraph.", "Second paragraph."] }), "json");
    expect(stringArray.text).toBe("First paragraph. Second paragraph.");

    const textItems = normalizeTranscript(
      JSON.stringify({ items: [{ speakerName: "Host", text: "Welcome." }] }),
      "json",
    );
    expect(textItems.text).toBe("Host: Welcome.");

    const topLevelText = normalizeTranscript(JSON.stringify({ text: "One plain transcript body." }), "json");
    expect(topLevelText.text).toBe("One plain transcript body.");
  });

  it("normalizes plain text whitespace", () => {
    const result = normalizeTranscript("hello   world\r\n\r\n\r\nnext  line", "txt");
    expect(result.text).toBe("hello world\n\nnext line");
  });
});

describe("htmlToText", () => {
  it("strips tags, scripts, and decodes entities", () => {
    const html = `<html><script>alert(1)</script><body><p>Hello &amp; welcome.</p><p>Second&nbsp;para</p></body></html>`;
    const text = htmlToText(html);
    expect(text).toBe("Hello & welcome.\nSecond para");
    expect(text).not.toContain("alert");
  });
});
